### ISSUE TITLE
adding more pictures?

### ISSUE THREAD

**Issue by cendarcy** [Charmelsippio/GrilledCheeseRepo#1]
Adding more pictures to image gallery?

**Comment by Charmelsippio** [comment]
Hi Guys,

We need to make sure that we have linked to each other's pages for the nav. If your nav isn't lining up properly, check the CSS from the another page as a guide. *ALSO MAKE SURE YOUR NAME IS IN YOUR CODE FOR THE HTML AND CSS PAGES FOR YOUR RESPECTIVE WORK!!!*

**Comment by cendarcy** [comment]
Thanks for this!

**Comment by Charmelsippio** [comment]
*ALSO MAKE SURE YOUR NAME IS IN YOUR CODE FOR THE HTML AND CSS PAGES FOR YOUR RESPECTIVE WORK!!!*

**Comment by davissen** [comment]
cheese breads and sandwiches added

**Comment by Charmelsippio** [comment]
Davissen has updated the page!
